global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring'